version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      POSTGRES_USER: myuser          
      POSTGRES_PASSWORD: mypassword   
      POSTGRES_DB: mydatabase      
    ports:
      - "5432:5432"  
    volumes:
      - postgres_data:/var/lib/postgresql/data  
    networks:
      - my_network
    restart: always 
# Volumes to persist data
volumes:
  postgres_data:

# Network definition (optional)
networks:
  my_network:
    driver: bridge
